# Generated by Django 5.1 on 2024-08-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0004_tweet_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tweet_images/"),
        ),
    ]
