# Generated by Django 5.1 on 2024-08-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0005_tweet_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="dark_mode",
            field=models.BooleanField(default=False),
        ),
    ]
