# Generated by Django 5.1 on 2024-08-20 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0006_userprofile_dark_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="dark_mode",
        ),
    ]
